Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace GhazwulShaf.Controllers
{
    public class AboutController : Controller
    {
        // GET: AboutController
        public IActionResult Index()
        {
            return View("/Views/Home/About/Index.cshtml");
        }

    }
}

Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace GhazwulShaf.Controllers
{
    public class ContactController : Controller
    {
        // GET: ContactController
        public ActionResult Index()
        {
            return View("/Views/Home/Contact/Index.cshtml");
        }

    }
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;

namespace GhazwulShaf.Controllers
{
    public class ProjectsController : Controller
    {
        // GET: ProjectsController
        public ActionResult Index()
        {
            return View("/Views/Home/Projects/Index.cshtml");
        }

        // GET: Project Details
        public IActionResult Detail(int id)
        {
            ViewData["Id"] = id;
            return View("/Views/Home/Projects/Detail.cshtml");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GhazwulShaf</title>
    <script type="importmap"></script>

    <meta name="author" content="Ghazwul Shaf">
    <meta name="description" content="@ViewData["Description"]">

    <!-- Bootstrap CSS
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> -->

    <!-- Tailwind CSS -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/output.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GhazwulShaf.styles.css" asp-append-version="true" />
</head>

<body class="relative min-h-screen pb-[78px]">

    <header class="sticky top-0 z-50 transition-spacing duration-500 bg-white">
        <div id="nav-wrapper" class="relative w-full h-full px-4 sm:px-12 lg:px-24 2xl:px-48 py-12 has-[sticky]:py-4">
            <nav class="flex justify-between xl:justify-start gap-8 ">

                <a id="brand" asp-controller="Home"- asp-action="Index" class="text-2xl sm:text-3xl font-bold">
                    <span>GhazwulShaf</span>
                </a>

                <button id="nav-menu-button" class="block md:hidden"><i data-feather="menu"></i></button>

                <div id="nav-menu" class="absolute top-full left-0 md:relative w-full md:w-fit hidden md:flex flex-col md:flex-row items-stretch md:items-end md:gap-8 font-semibold xl:text-xl *:px-4 *:sm:px-12 *:py-4 *:md:p-0">
                    <a asp-controller="About" asp-action="Index" class="bg-white">About</a>
                    <a asp-controller="Learn" asp-action="Index" class="bg-white">Learn</a>
                    <a asp-controller="Projects" asp-action="Index" class="bg-white">Projects</a>
                    <a asp-controller="Contact" asp-action="Index" class="bg-white">Contact</a>
                </div>
            </nav>
        </div>
    </header>

    <main role="main" class="z-40">
        @RenderBody()
    </main>

    <footer class="absolute bottom-0 w-full whitespace-nowrap leading-[60px] px-4 sm:px-12 lg:px-24 2xl:px-48 py-2 bg-neutral-200">
        <partial name="Layout/_Footer"></partial>
    </footer>

    <script>

        // Sizing Header on sticky
        document.addEventListener('scroll', () => {

            const header = document.querySelector("header");
            const headerHeight = header.offsetHeight;

            const headerNav = document.querySelector('#nav-wrapper');
            if (header.offsetTop > headerHeight)
            {
                headerNav.classList.replace('py-12', 'py-4');
            }
            else
            {
                headerNav.classList.replace('py-4', 'py-12');
            }
        })

        const navMenuButton = document.querySelector('#nav-menu-button');
        const navMenu = document.querySelector('#nav-menu');
        let navMenuState = "hidden";

        navMenuButton.addEventListener('click', () => {
            if (navMenuState == "hidden") {
                navMenu.classList.replace('hidden', 'flex');
                navMenuState = "show";
            } else if (navMenuState == "show") {
                navMenu.classList.replace('flex', 'hidden');
                navMenuState = "hidden";
            }
        })

    </script>

    <!-- Feather Icons -->
    <script src="~/lib/feathericons\dist\js\feather.min.js"></script>
    <script>
        feather.replace();
    </script>

    <!-- Bootstrap CSS
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> -->
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GhazwulShaf</title>
    <script type="importmap"></script>

    <!-- Bootstrap CSS
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> -->

    <!-- Tailwind CSS -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/output.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GhazwulShaf.styles.css" asp-append-version="true" />
</head>

<body>

    <main role="main">
        @RenderBody()
    </main>

    <!-- Feather Icons -->
    <script src="~/lib/feathericons\dist\js\feather.min.js"></script>
    <script>
        feather.replace();
    </script>

    <!-- Bootstrap CSS
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> -->
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GhazwulShaf</title>
    <script type="importmap"></script>

    <!-- Bootstrap CSS
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> -->

    <!-- Tailwind CSS -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/output.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GhazwulShaf.styles.css" asp-append-version="true" />

    <!-- Summernote -->
    <link rel="stylesheet" href="~/lib/summernote/dist/summernote-lite.min.css" />
</head>

<body>

    <div id="dashboard-layout" class="w-full min-h-screen flex flex-row items-start">
        <div id="dashboard-sidebar" class="flex-none sticky top-0 min-h-screen z-40 overflow-y-auto flex flex-col items-center justify-between bg-gray-800 text-white pb-4">
            <div>
                <div class="flex gap-4">
                    <a id="dashboard-brand" href="@Url.Action("Index", "Home")" class="hidden xl:block px-2 sm:px-4 py-4">
                        <h4>GhazwulShaf</h4>
                        <span>@AuthUser.Role</span>
                    </a>
                    <button type="button" id="dashboard-navbar-menu-button" class="xl:hidden px-2 sm:px-4 py-4">
                        <i data-feather="menu" class="h-4 sm:h-5"></i>
                    </button>
                </div>

                @functions {
                    // function to get route and set nav active 
                    public string IsActive(string controller)
                    {
                        var currentController = ViewContext.RouteData.Values["controller"]?.ToString();
                        if (currentController == controller)
                            return "active";
                        
                        return "";
                    }
                }
                <nav id="dashboard-navbar" class="w-full mb-24 flex flex-col items-stretch gap-0 *:px-2 *:sm:px-4 *:py-3 *:flex *:items-center *:gap-2">
                    <a href="@Url.Action("Index", "Dashboard")" class="@IsActive("Dashboard")">
                        <i data-feather="layout" class="h-4 sm:h-5"></i><span class="hidden xl:inline">Dashboard</span>
                    </a>
                    <a href="@Url.Action("Index", "DashboardMasterdata")" class="@IsActive("DashboardMasterdata")">
                        <i data-feather="file-text" class="h-4 sm:h-5"></i><span class="hidden xl:inline">Masterdata</span>
                    </a>
                    <a href="@Url.Action("Index", "DashboardAbout")" class="@IsActive("DashboardAbout")">
                        <i data-feather="user" class="h-4 sm:h-5"></i><span class="hidden xl:inline">About</span>
                    </a>
                    <a href="@Url.Action("Index", "DashboardLearn")" class="@IsActive("DashboardLearn")">
                        <i data-feather="book" class="h-4 sm:h-5"></i><span class="hidden xl:inline">Learn</span>
                    </a>
                    <a href="@Url.Action("Index", "DashboardProjects")" class="@IsActive("DashboardProjects")">
                        <i data-feather="code" class="h-4 sm:h-5"></i><span class="hidden xl:inline">Projects</span>
                    </a>
                    <a href="@Url.Action("Index", "DashboardContact")" class="@IsActive("DashboardContact")">
                        <i data-feather="phone" class="h-4 sm:h-5"></i><span class="hidden xl:inline">Contact</span>
                    </a>
                </nav>
            </div>
            
            <div class="w-full flex px-2 sm:px-4">
                <form id="auth-logout" name="auth-logout" method="post" action="@Url.Action("Logout", "Auth")" hidden></form>
                <button type="submit" form="auth-logout" id="dashboard-logout-button" class="grow flex items-center justify-center gap-2 xl:bg-black rounded-md py-3"><i data-feather="log-out" class="inline xl:hidden h-5"></i><span class="hidden xl:inline">Logout</span></button>
            </div>
        </div>
        
        <div id="content" class="flex-1 w-auto min-h-screen bg-gray-200">
            <header class="w-full bg-white px-2 sm:px-4 lg:px-12 py-2 sm:py-4">
                <h4>@ViewData["Title"]</h4>
            </header>

            <main role="main">
                @RenderBody()
            </main>
        </div>
    </div>

    <!-- Feather Icons -->
    <script src="~/lib/feathericons\dist\js\feather.min.js"></script>
    <script>
        feather.replace();
    </script>

    <!-- Bootstrap CSS
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> -->
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Summernote -->
    <script src="~/lib/summernote/dist/summernote-lite.min.js"></script>
    <script>
        $(document).ready(function() {
            // init summernote
            $('#summernote').summernote({
                placeholder: 'Write the contents in here',
                tabsize: 2,
                height: 480,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'underline', 'clear']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'video']],
                    ['view', ['fullscreen', 'codeview', 'help']]
                ],
                fontNames: ['Manrope'],
                fontNamesIgnoreCheck: ['Manrope'],
                addDefaultFonts: false,
            });
        })
    </script>

    <script>
        const dashboard = document.querySelector('#dashboard-layout');
        const sidebar = document.querySelector('#dashboard-sidebar');
        const navbarMenuButton = document.querySelector('#dashboard-navbar-menu-button');
        const navbar = document.querySelector('#dashboard-navbar');
        const brand = document.querySelector('#dashboard-brand');
        const logoutButton = document.querySelector('#dashboard-logout-button');
        const content = document.querySelector('#content');

        var sidebarWidth = sidebar.clientWidth;
        
        content.style.maxWidth = `${screen.width - sidebarWidth}px`;

        var sidebarState = "collapsed";

        navbarMenuButton.addEventListener('click', () => {
            ToggleSidebar();
        });

        function ToggleSidebar() {
            if (sidebarState == "collapsed") {
                content.style.marginLeft = `${sidebarWidth}px`;
                sidebarState = "uncollapsed";
            } else if (sidebarState == "uncollapsed") {
                content.style.marginLeft = `0px`;
                sidebarState = "collapsed";
            }
            sidebar.classList.toggle('sticky');
            sidebar.classList.toggle('fixed');
            brand.classList.toggle('hidden');
            const navbarItemsText = navbar.querySelectorAll('span');
            navbarItemsText.forEach((itemText) => {
                itemText.classList.toggle('hidden');
            })
            logoutButton.classList.toggle('bg-black');
            const logoutButtonText = logoutButton.querySelector('span');
            logoutButtonText.classList.toggle('hidden');
        }
    </script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_Pagination.cshtml
@{
    PagingInfo PagingInfo = ViewBag.PagingInfo;
    int CurrentPage = PagingInfo.CurrentPage;
    int TotalPages = PagingInfo.TotalPages;
}

<div class="pagination">
    <button class="pagination-item" @(CurrentPage == 1 ? "disabled" : "") data-page-number="@(CurrentPage - 1)" onclick="SetPage(this)"><i data-feather="chevron-left" class="w-4"></i></button>
    <button class="pagination-item @(CurrentPage == 1 ? "active" : "")" data-page-number="1" onclick="SetPage(this)">1</button>
    <div class="@(CurrentPage >= 4 ? "flex" : "hidden") items-center"><i data-feather="more-horizontal" class="inline w-3"></i></div>
@if (TotalPages > 1)
{
    @for (int i = CurrentPage > 2 ? CurrentPage - 1 : 2; i <= (TotalPages - CurrentPage >= 2 ? CurrentPage + 1 : TotalPages - 1); i++)
    {
    <button class="pagination-item @(i == CurrentPage ? "active" : "")" data-page-number="@i" onclick="SetPage(this)">@i</button>
    }
    <div class="@(TotalPages - CurrentPage >= 3 ? "flex" : "hidden") flex items-center"><i data-feather="more-horizontal" class="inline w-3"></i></div>
    <button class="pagination-item @(CurrentPage == TotalPages ? "active" : "")" data-page-number="@TotalPages" onclick="SetPage(this)">@TotalPages</button>
}
    <button class="pagination-item" @(CurrentPage == TotalPages ? "disabled" : "") data-page-number="@(CurrentPage + 1)" onclick="SetPage(this)"><i data-feather="chevron-right" class="w-4"></i></button>
</div>