Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace GhazwulShaf.Models;

public class Contact
{
    public string Title { get; set; } = default!;
    public string Description { get; set; } = default!;
    
    [DataType(DataType.EmailAddress)]
    public string Email { get; set; } = default!;

    public string Phone { get; set; } = default!;
    public string Address { get; set; } = default!;
    public List<ContactLink> Links { get; set; } = new List<ContactLink>();
}

public class ContactLink
{
    public int Id { get; set; } = default!;
    public string Name { get; set; } = default!;
    public string Icon { get; set; } = default!;
    
    [DataType(DataType.Url)]
    public string Url { get; set; } = default!;
}

Controllers/Admin/Dashboard/DashboardAboutController.cs
using GhazwulShaf.Models;
using GhazwulShaf.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GhazwulShaf.Controllers.Admin.Dashboard
{
    [Authorize(Roles = "Admin")]
    [Route("/Admin/Dashboard/About")]
    public class DashboardAboutController : Controller
    {
        private readonly string _profilePhotoFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "profile");
        private readonly string _cvFileFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "files");
        private readonly AboutProfileService _profileService;
        private readonly AboutSectionService _sectionService;

        public DashboardAboutController(AboutProfileService profileService, AboutSectionService sectionsService)
        {
            _profileService = profileService;
            _sectionService = sectionsService;

            if (!Directory.Exists(_profilePhotoFolder))
                Directory.CreateDirectory(_profilePhotoFolder);

            if (!Directory.Exists(_cvFileFolder))
                Directory.CreateDirectory(_cvFileFolder);
        }

        // GET: DashboardAboutController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View("/Views/Admin/Dashboard/About/Index.cshtml",
                new About {
                    Profile = await _profileService.GetAsync(),
                    Sections = await _sectionService.GetAllAsync()
                }
            );
        }

        // POST: Update About Profile
        [HttpPost]
        [Route("Update")]
        public async Task<IActionResult> Update(About About, IFormFile ProfilePhotoFile, IFormFile ProfileCVFile)
        {
            if (About.Profile != null)
            {
                if (ProfilePhotoFile != null && ProfilePhotoFile.Length > 0)
                {
                    var photoFileName = Path.GetFileName(ProfilePhotoFile.FileName);
                    var photoFilePath = Path.Combine(_profilePhotoFolder, photoFileName);

                    if (System.IO.File.Exists(photoFilePath))
                        System.IO.File.Delete(photoFilePath);

                    using var stream = new FileStream(photoFilePath, FileMode.Create);
                    await ProfilePhotoFile.CopyToAsync(stream);

                    About.Profile.Photo = "/images/profile/" + photoFileName;
                }

                if (ProfileCVFile != null && ProfileCVFile.Length > 0)
                {
                    var cvFileName = "curriculumvitae" + Path.GetExtension(ProfileCVFile.FileName);
                    var cvFilePath = Path.Combine(_cvFileFolder, cvFileName);

                    if (System.IO.File.Exists(cvFilePath))
                        System.IO.File.Delete(cvFilePath);

                    using var stream = new FileStream(cvFilePath, FileMode.Create);
                    await ProfileCVFile.CopyToAsync(stream);

                    About.Profile.CV = cvFileName;
                }

                await _profileService.UpdateAsync(About.Profile);

                TempData["SuccessMessage"] = "Profile has been updated!";
                return RedirectToAction(nameof(Index));
            }

            TempData["ErrorMessage"] = "Profile updating was error!";
            return View("/Views/Admin/Dashboard/About/Index.cshtml", About);
        }

        // GET: Add Section
        [HttpGet]
        [Route("Sections/Add")]
        public IActionResult AddSection()
        {
            ViewBag.Session = "Add";
            ViewBag.Action = "AddSection";

            var view = "/Views/Admin/Dashboard/About/_SectionForm.cshtml";
            var section = new AboutSection();

            return PartialView(view, section);
        }

        // POST: Add Section
        [HttpPost]
        [Route("Sections/Add")]
        public async Task<IActionResult> AddSection(AboutSection section)
        {
            await _sectionService.AddAsync(section);
            return RedirectToAction(nameof(Index));
        }

        // POST: Edit Section
        [HttpGet]
        [Route("Sections/{id}/Edit")]
        public async Task<IActionResult> EditSection(int id)
        {
            ViewBag.Session = "Edit";
            ViewBag.Action = "EditSection";

            var view = "/Views/Admin/Dashboard/About/_SectionForm.cshtml";
            var section = await _sectionService.GetByIdAsync(id);

            return PartialView(view, section);
        }

        // POST: Edit Section
        [HttpPost]
        [Route("Sections/{id}/Edit")]
        public async Task<IActionResult> EditSection(AboutSection section)
        {
            await _sectionService.UpdateAsync(section);
            return RedirectToAction(nameof(Index));
        }

        // POST: Delete Section
        [HttpPost]
        [Route("Sections/{id}/Delete")]
        public async Task<IActionResult> DeleteSection(int id)
        {
            await _sectionService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        // GET: Add Section Item
        [HttpGet]
        [Route("Sections/{sectionId}/Add")]
        public async Task<IActionResult> AddSectionItem(int sectionId)
        {
            var view = "/Views/Admin/Dashboard/About/_SectionItem.cshtml";
            var section = await _sectionService.GetByIdAsync(sectionId);

            ViewBag.Id = section.Id;
            ViewBag.Title = section.Title;
            ViewBag.Session = "Add";
            ViewBag.Action = "AddSectionItem";

            return PartialView(view, new AboutSectionItem());
        }

        // POST: Add Section Item
        [HttpPost]
        [Route("Sections/{sectionId}/Add")]
        public async Task<IActionResult> AddSectionItem(int sectionId, AboutSectionItem item)
        {
            await _sectionService.AddItemAsync(sectionId, item);
            return RedirectToAction(nameof(Index));
        }

        // GET: Edit Section Item
        [HttpGet]
        [Route("Sections/{sectionId}/{itemId}/Edit")]
        public async Task<IActionResult> EditSectionItem(int sectionId, int itemId)
        {
            var view = "/Views/Admin/Dashboard/About/_SectionItem.cshtml";
            var section = await _sectionService.GetByIdAsync(sectionId);
            var item = await _sectionService.GetItemByIdAsync(sectionId, itemId);

            ViewBag.Id = section.Id;
            ViewBag.Title = section.Title;
            ViewBag.Session = "Edit";
            ViewBag.Action = "EditSectionItem";

            return PartialView(view, item);
        }

        // POST: Edit Section Item
        [HttpPost]
        [Route("Sections/{sectionId}/{itemId}/Edit")]
        public async Task<IActionResult> EditSectionItem(int sectionId, AboutSectionItem item)
        {
            await _sectionService.UpdateItemAsync(sectionId, item);
            return RedirectToAction(nameof(Index));
        }

        // POST: Delete Section Item
        [HttpPost]
        [Route("Sections/{sectionId}/{itemId}/Delete")]
        public async Task<IActionResult> DeleteSectionItem(int sectionId, int itemId)
        {
            await _sectionService.DeleteItemAsync(sectionId, itemId);
            return RedirectToAction(nameof(Index));
        }

        // POST: Reorder Section Items
        [HttpPost]
        [Route("Sections/{sectionId}/Reorder")]
        public async Task<IActionResult> ReorderSectionItems(AboutSection section)
        {
            await _sectionService.ReorderItemsAsync(section);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/Admin/Dashboard/DashboardContactController.cs
using GhazwulShaf.Models;
using GhazwulShaf.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GhazwulShaf.Controllers.Admin.Dashboard
{
    [Authorize(Roles = "Admin")]
    [Route("/Admin/Dashboard/Contact")]
    public class DashboardContactController : Controller
    {
        private readonly ContactService _contactService;

        public DashboardContactController(ContactService contactService)
        {
            _contactService = contactService;
        }

        // GET: DashboardContactController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var contact = await _contactService.GetAsync();

            return View("/Views/Admin/Dashboard/Contact/Index.cshtml", contact);
        }

        // POST: Update
        [HttpPost]
        [Route("Update")]
        public async Task<IActionResult> Update(Contact contact)
        {
            await _contactService.UpdateAsync(contact);
            return RedirectToAction(nameof(Index));
        }

        // GET: Render Links Item
        [HttpGet]
        [Route("Links/Add")]
        public ActionResult AddLinksItem(int itemId)
        {
            ViewBag.ItemId = itemId;
            return PartialView("/Views/Admin/Dashboard/Contact/_LinksItem.cshtml", new Contact());
        }
    }
}

Controllers/Admin/Dashboard/DashboardController.cs
using GhazwulShaf.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GhazwulShaf.Controllers.Admin.Dashboard
{
    [Authorize(Roles = "Admin")]
    [Route("/Admin/Dashboard/")]
    public class DashboardController : Controller
    {
        // GET: DashboardController
        [HttpGet]
        public ActionResult Index()
        {
            return View("/Views/Admin/Dashboard/Index.cshtml");
        }
    }
}

Controllers/Admin/Dashboard/DashboardMasterdataController.cs
using GhazwulShaf.Models;
using GhazwulShaf.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GhazwulShaf.Controllers.Admin.Dashboard
{
    [Authorize(Roles = "Admin")]
    [Route("admin/dashboard/masterdata")]
    public class DashboardMasterdataController : Controller
    {
        private readonly MasterdataService _masterdataService;

        public DashboardMasterdataController(MasterdataService masterdataService)
        {
            _masterdataService = masterdataService;
        }

        // GET: Dashboard Masterdata Page
        [HttpGet, Route("")]
        public async Task<IActionResult> Index()
        {
            var masterdata = await _masterdataService.GetAsync();

            return View("/Views/Admin/Dashboard/Masterdata/Index.cshtml", masterdata);
        }

        // POST: Update Welcome Text
        [HttpPost, Route("welcome/update")]
        public async Task<IActionResult> UpdateWelcome(Masterdata masterdata)
        {
            var welcome = masterdata.Welcome;
            await _masterdataService.UpdateWelcomeAsync(welcome);
            return RedirectToAction(nameof(Index));
        }

        // POST: Update Masterdata
        [HttpPost, Route("types/update")]
        public async Task<IActionResult> UpdateTypes(Masterdata masterdata)
        {
            var types = masterdata.Types;
            await _masterdataService.UpdateTypesAsync(types);
            return RedirectToAction(nameof(Index));
        }

        // GET: Project Types New Item Partial
        [HttpGet, Route("types/add")]
        public IActionResult AddTypesItem(int typeId)
        {
            ViewBag.TypeId = typeId;

            return PartialView("/Views/Admin/Dashboard/Masterdata/_ProjectType.cshtml", new Masterdata());
        }
    }
}

Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace GhazwulShaf.Controllers
{
    public class ContactController : Controller
    {
        // GET: ContactController
        public ActionResult Index()
        {
            return View("/Views/Home/Contact/Index.cshtml");
        }

    }
}

Controllers/Home/ContactController.cs
using GhazwulShaf.Models;
using GhazwulShaf.Services;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Mvc;
using MimeKit;

namespace GhazwulShaf.Controllers.Home
{
    [Route("/contact")]
    public class ContactController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly ContactService _contactService;

        public ContactController(IConfiguration configuration, ContactService contactService)
        {
            _configuration = configuration;
            _contactService = contactService;
        }

        // GET: View Home Contact Page
        [HttpGet, Route("")]
        public async Task<IActionResult> Index()
        {
            var contact = await _contactService.GetAsync();
            return View("/Views/Home/Contact/Index.cshtml", contact);
        }

        // POST: Send Message to Email
        [HttpPost, Route("send-message")]
        public async Task<IActionResult> SendMessage(string name, string email, string subject, string message)
        {
            if (name != null && email != null && subject != null && message != null)
            {
                try
                {
                    var emailService = new MimeMessage();
                    emailService.From.Add(new MailboxAddress(name, email));
                    emailService.To.Add(new MailboxAddress("Admin", _configuration["EmailSettings:RecipientEmail"]));
                    emailService.Subject = subject;
                    emailService.Body = new TextPart("plain");

                    using var smtp = new SmtpClient();
                    smtp.Connect(_configuration["EmailSettings:SmtpServer"], int.Parse(_configuration["EmailSettings:SmtpPort"]!), true);
                    smtp.Send(emailService);
                    smtp.Disconnect(true);

                    ViewData["Send_Success"] = "Message sent successfully";
                }
                catch (Exception ex)
                {
                    ViewData["Send_Error"] = $"Failed to send message: {ex.Message}";
                }
            }

            var contact = await _contactService.GetAsync();
            return View("/Views/Home/Contact/Index.cshtml", contact);
        }
    }
}

Views/Admin/Dashboard/Contact/Index.cshtml
@model Contact
@{
    Layout = "_LayoutDashboard";
    ViewData["Title"] = "Contact";
    
    var linksCount = Model.Links.Count;
}

<div class="px-2 sm:px-4 lg:px-12 pt-2 sm:pt-4 pb-6 [&_.note-editor]:text-sm [&_.note-editor]:sm:text-base">
    <div class="card p-2 sm:p-4">
        <form method="post" asp-action="Update" asp-controller="DashboardContact" class="*:mt-4">
            <div class="first:mt-0">
                <label class="label">Title:</label>
                <input type="text" class="input" asp-for="Title" placeholder="Get in Touch">
            </div>

            <div>
                <label class="label">Description:</label>
                <textarea id="description" asp-for="Description"></textarea>
            </div>

            <div class="grid grid-cols-1 sm:grid-cols-3 gap-2">
                <div>
                    <label for="" class="label">Email:</label>
                    <input type="email" class="input" asp-for="Email" placeholder="email@example.com">
                </div>

                <div>
                    <label for="" class="label">Phone:</label>
                    <input type="text" class="input" asp-for="Phone" placeholder="+0 123 456 789">
                </div>

                <div>
                    <label for="" class="label">Address:</label>
                    <input type="text" class="input" asp-for="Address" placeholder="Example St.">
                </div>
            </div>

            <div>
                <div class="*:inline">
                    <label for="" class="label">Links:</label>&nbsp;
                    <button type="button" class="underline" onclick="AddItem()">add</button>
                </div>

                <div id="links-items" class="*:mt-2">
                @for (var index = 0; index < Model.Links.Count; index++)
                {
                    ViewBag.State = "Show";
                    ViewBag.ItemId = index;
                    <partial name="/Views/Admin/Dashboard/Contact/_LinksItem.cshtml" for="@Model"></partial>
                }
                </div>
            </div>

            <div class="text-center last:mt-8 mb-2 sm:mb-0">
                <button type="submit" class="button button-dark w-full sm:w-fit py-1">Save</button>
            </div>
        </form>
    </div>
</div>

@section Scripts
{
<script>
    $(document).ready(() => {
        $('#description').summernote({
            placeholder: 'Write the contents in here',
            tabsize: 2,
            height: 300,
            toolbar: [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'video']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ],
            fontNames: ['Manrope'],
            fontNamesIgnoreCheck: ['Manrope'],
            addDefaultFonts: false,
        });
    })
</script>

<script>
    var itemId = @Model.Links.Count;

    function AddItem() {
        var data = {
            itemId: itemId++
        }

        $.ajax({
            url: '@Url.Action("AddLinksItem", "DashboardContact")',
            data: data,
            success: (response) => {
                $('#links-items').append(response);
                feather.replace();
            }
        })
    }

    function DeleteItem(itemId) {
        var item = document.querySelector('#' + itemId);

        if (confirm('Are you sure you want to delete this item?'))
            item.remove();
    }
</script>
}

Views/Admin/Dashboard/Contact/_LinksItem.cshtml
@model Contact
@{
    int ItemId = ViewBag.ItemId;
}

<div id="links-item_@ItemId" class="flex items-start gap-1 sm:gap-2">
    <div class="first:mt-0 w-full border border-gray-200 p-2 grid grid-cols-2 sm:grid-cols-3 gap-2">
        <input type="hidden" name="Links[@ItemId].Id" value="@(ViewBag.State == "Show" ? Model.Links[ItemId].Id : null)">

        <div>
            <label for="" class="label">Name:</label>
            <input type="text" class="input" name="Links[@ItemId].Name" value="@(ViewBag.State == "Show" ? Model.Links[ItemId].Name : null)" placeholder="Example">
        </div>

        <div>
            <label for="" class="label">Icon:</label>
            <input type="text" class="input" name="Links[@ItemId].Icon" value="@(ViewBag.State == "Show" ? Model.Links[ItemId].Icon : null)" placeholder="example" title="Get the icon name from feather icons">
        </div>

        <div class="col-span-2 sm:col-span-1">
            <label for="" class="label">Url:</label>
            <input type="url" class="input" name="Links[@ItemId].Url" value="@(ViewBag.State == "Show" ? Model.Links[ItemId].Url : null)" placeholder="https://example.com">
        </div>
    </div>

    <div id="links-item_@ItemId-actions">
        <button type="button" class="text-red-500" onclick="DeleteItem('links-item_@ItemId')"><i data-feather="trash" class="h-4"></i></button>
    </div>
</div>