Models/About.cs
namespace GhazwulShaf.Models;

public class About
{
    public AboutProfile Profile { get; set; } = new AboutProfile();
    public List<AboutSection> Sections { get; set; } = [];
}

Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace GhazwulShaf.Controllers
{
    public class AboutController : Controller
    {
        // GET: AboutController
        public IActionResult Index()
        {
            return View("/Views/Home/About/Index.cshtml");
        }

    }
}

Controllers/Admin/Dashboard/DashboardAboutController.cs
using GhazwulShaf.Models;
using GhazwulShaf.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GhazwulShaf.Controllers.Admin.Dashboard
{
    [Authorize(Roles = "Admin")]
    [Route("/Admin/Dashboard/About")]
    public class DashboardAboutController : Controller
    {
        private readonly string _profilePhotoFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "profile");
        private readonly string _cvFileFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "files");
        private readonly AboutProfileService _profileService;
        private readonly AboutSectionService _sectionService;

        public DashboardAboutController(AboutProfileService profileService, AboutSectionService sectionsService)
        {
            _profileService = profileService;
            _sectionService = sectionsService;

            if (!Directory.Exists(_profilePhotoFolder))
                Directory.CreateDirectory(_profilePhotoFolder);

            if (!Directory.Exists(_cvFileFolder))
                Directory.CreateDirectory(_cvFileFolder);
        }

        // GET: DashboardAboutController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View("/Views/Admin/Dashboard/About/Index.cshtml",
                new About {
                    Profile = await _profileService.GetAsync(),
                    Sections = await _sectionService.GetAllAsync()
                }
            );
        }

        // POST: Update About Profile
        [HttpPost]
        [Route("Update")]
        public async Task<IActionResult> Update(About About, IFormFile ProfilePhotoFile, IFormFile ProfileCVFile)
        {
            if (About.Profile != null)
            {
                if (ProfilePhotoFile != null && ProfilePhotoFile.Length > 0)
                {
                    var photoFileName = Path.GetFileName(ProfilePhotoFile.FileName);
                    var photoFilePath = Path.Combine(_profilePhotoFolder, photoFileName);

                    if (System.IO.File.Exists(photoFilePath))
                        System.IO.File.Delete(photoFilePath);

                    using var stream = new FileStream(photoFilePath, FileMode.Create);
                    await ProfilePhotoFile.CopyToAsync(stream);

                    About.Profile.Photo = "/images/profile/" + photoFileName;
                }

                if (ProfileCVFile != null && ProfileCVFile.Length > 0)
                {
                    var cvFileName = "curriculumvitae" + Path.GetExtension(ProfileCVFile.FileName);
                    var cvFilePath = Path.Combine(_cvFileFolder, cvFileName);

                    if (System.IO.File.Exists(cvFilePath))
                        System.IO.File.Delete(cvFilePath);

                    using var stream = new FileStream(cvFilePath, FileMode.Create);
                    await ProfileCVFile.CopyToAsync(stream);

                    About.Profile.CV = cvFileName;
                }

                await _profileService.UpdateAsync(About.Profile);

                TempData["SuccessMessage"] = "Profile has been updated!";
                return RedirectToAction(nameof(Index));
            }

            TempData["ErrorMessage"] = "Profile updating was error!";
            return View("/Views/Admin/Dashboard/About/Index.cshtml", About);
        }

        // GET: Add Section
        [HttpGet]
        [Route("Sections/Add")]
        public IActionResult AddSection()
        {
            ViewBag.Session = "Add";
            ViewBag.Action = "AddSection";

            var view = "/Views/Admin/Dashboard/About/_SectionForm.cshtml";
            var section = new AboutSection();

            return PartialView(view, section);
        }

        // POST: Add Section
        [HttpPost]
        [Route("Sections/Add")]
        public async Task<IActionResult> AddSection(AboutSection section)
        {
            await _sectionService.AddAsync(section);
            return RedirectToAction(nameof(Index));
        }

        // POST: Edit Section
        [HttpGet]
        [Route("Sections/{id}/Edit")]
        public async Task<IActionResult> EditSection(int id)
        {
            ViewBag.Session = "Edit";
            ViewBag.Action = "EditSection";

            var view = "/Views/Admin/Dashboard/About/_SectionForm.cshtml";
            var section = await _sectionService.GetByIdAsync(id);

            return PartialView(view, section);
        }

        // POST: Edit Section
        [HttpPost]
        [Route("Sections/{id}/Edit")]
        public async Task<IActionResult> EditSection(AboutSection section)
        {
            await _sectionService.UpdateAsync(section);
            return RedirectToAction(nameof(Index));
        }

        // POST: Delete Section
        [HttpPost]
        [Route("Sections/{id}/Delete")]
        public async Task<IActionResult> DeleteSection(int id)
        {
            await _sectionService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        // GET: Add Section Item
        [HttpGet]
        [Route("Sections/{sectionId}/Add")]
        public async Task<IActionResult> AddSectionItem(int sectionId)
        {
            var view = "/Views/Admin/Dashboard/About/_SectionItem.cshtml";
            var section = await _sectionService.GetByIdAsync(sectionId);

            ViewBag.Id = section.Id;
            ViewBag.Title = section.Title;
            ViewBag.Session = "Add";
            ViewBag.Action = "AddSectionItem";

            return PartialView(view, new AboutSectionItem());
        }

        // POST: Add Section Item
        [HttpPost]
        [Route("Sections/{sectionId}/Add")]
        public async Task<IActionResult> AddSectionItem(int sectionId, AboutSectionItem item)
        {
            await _sectionService.AddItemAsync(sectionId, item);
            return RedirectToAction(nameof(Index));
        }

        // GET: Edit Section Item
        [HttpGet]
        [Route("Sections/{sectionId}/{itemId}/Edit")]
        public async Task<IActionResult> EditSectionItem(int sectionId, int itemId)
        {
            var view = "/Views/Admin/Dashboard/About/_SectionItem.cshtml";
            var section = await _sectionService.GetByIdAsync(sectionId);
            var item = await _sectionService.GetItemByIdAsync(sectionId, itemId);

            ViewBag.Id = section.Id;
            ViewBag.Title = section.Title;
            ViewBag.Session = "Edit";
            ViewBag.Action = "EditSectionItem";

            return PartialView(view, item);
        }

        // POST: Edit Section Item
        [HttpPost]
        [Route("Sections/{sectionId}/{itemId}/Edit")]
        public async Task<IActionResult> EditSectionItem(int sectionId, AboutSectionItem item)
        {
            await _sectionService.UpdateItemAsync(sectionId, item);
            return RedirectToAction(nameof(Index));
        }

        // POST: Delete Section Item
        [HttpPost]
        [Route("Sections/{sectionId}/{itemId}/Delete")]
        public async Task<IActionResult> DeleteSectionItem(int sectionId, int itemId)
        {
            await _sectionService.DeleteItemAsync(sectionId, itemId);
            return RedirectToAction(nameof(Index));
        }

        // POST: Reorder Section Items
        [HttpPost]
        [Route("Sections/{sectionId}/Reorder")]
        public async Task<IActionResult> ReorderSectionItems(AboutSection section)
        {
            await _sectionService.ReorderItemsAsync(section);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/Admin/Dashboard/DashboardContactController.cs
using GhazwulShaf.Models;
using GhazwulShaf.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GhazwulShaf.Controllers.Admin.Dashboard
{
    [Authorize(Roles = "Admin")]
    [Route("/Admin/Dashboard/Contact")]
    public class DashboardContactController : Controller
    {
        private readonly ContactService _contactService;

        public DashboardContactController(ContactService contactService)
        {
            _contactService = contactService;
        }

        // GET: DashboardContactController
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var contact = await _contactService.GetAsync();

            return View("/Views/Admin/Dashboard/Contact/Index.cshtml", contact);
        }

        // POST: Update
        [HttpPost]
        [Route("Update")]
        public async Task<IActionResult> Update(Contact contact)
        {
            await _contactService.UpdateAsync(contact);
            return RedirectToAction(nameof(Index));
        }

        // GET: Render Links Item
        [HttpGet]
        [Route("Links/Add")]
        public ActionResult AddLinksItem(int itemId)
        {
            ViewBag.ItemId = itemId;
            return PartialView("/Views/Admin/Dashboard/Contact/_LinksItem.cshtml", new Contact());
        }
    }
}

Controllers/Admin/Dashboard/DashboardController.cs
using GhazwulShaf.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GhazwulShaf.Controllers.Admin.Dashboard
{
    [Authorize(Roles = "Admin")]
    [Route("/Admin/Dashboard/")]
    public class DashboardController : Controller
    {
        // GET: DashboardController
        [HttpGet]
        public ActionResult Index()
        {
            return View("/Views/Admin/Dashboard/Index.cshtml");
        }
    }
}

Controllers/Admin/Dashboard/DashboardMasterdataController.cs
using GhazwulShaf.Models;
using GhazwulShaf.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GhazwulShaf.Controllers.Admin.Dashboard
{
    [Authorize(Roles = "Admin")]
    [Route("admin/dashboard/masterdata")]
    public class DashboardMasterdataController : Controller
    {
        private readonly MasterdataService _masterdataService;

        public DashboardMasterdataController(MasterdataService masterdataService)
        {
            _masterdataService = masterdataService;
        }

        // GET: Dashboard Masterdata Page
        [HttpGet, Route("")]
        public async Task<IActionResult> Index()
        {
            var masterdata = await _masterdataService.GetAsync();

            return View("/Views/Admin/Dashboard/Masterdata/Index.cshtml", masterdata);
        }

        // POST: Update Welcome Text
        [HttpPost, Route("welcome/update")]
        public async Task<IActionResult> UpdateWelcome(Masterdata masterdata)
        {
            var welcome = masterdata.Welcome;
            await _masterdataService.UpdateWelcomeAsync(welcome);
            return RedirectToAction(nameof(Index));
        }

        // POST: Update Masterdata
        [HttpPost, Route("types/update")]
        public async Task<IActionResult> UpdateTypes(Masterdata masterdata)
        {
            var types = masterdata.Types;
            await _masterdataService.UpdateTypesAsync(types);
            return RedirectToAction(nameof(Index));
        }

        // GET: Project Types New Item Partial
        [HttpGet, Route("types/add")]
        public IActionResult AddTypesItem(int typeId)
        {
            ViewBag.TypeId = typeId;

            return PartialView("/Views/Admin/Dashboard/Masterdata/_ProjectType.cshtml", new Masterdata());
        }
    }
}

Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;

namespace GhazwulShaf.Controllers;

public class FileController: Controller
{
    public IActionResult DownloadFile(string fileName)
    {
        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "files", fileName);

        if (!System.IO.File.Exists(filePath))
        {
            return NotFound("File not found!");
        }

        var fileBytes = System.IO.File.ReadAllBytes(filePath);

        return File(fileBytes, "application/octet-stream", fileName);
    }
}

Controllers/Home/AboutController.cs
using GhazwulShaf.Models;
using GhazwulShaf.Services;
using Microsoft.AspNetCore.Mvc;

namespace GhazwulShaf.Controllers.Home
{
    [Route("/about")]
    public class AboutController : Controller
    {
        private readonly AboutProfileService _profileService;
        private readonly AboutSectionService _sectionService;

        public AboutController(AboutProfileService profileService, AboutSectionService sectionService)
        {
            _profileService = profileService;
            _sectionService = sectionService;
        }

        // GET: AboutController
        public async Task<IActionResult> Index()
        {
            return View("/Views/Home/About/Index.cshtml",
                new About {
                    Profile = await _profileService.GetAsync(),
                    Sections = await _sectionService.GetAllAsync()
                }    
            );
        }
    }
}

Views/Admin/Dashboard/About/Index.cshtml
@model About

@{
    Layout = "_LayoutDashboard";
    ViewData["Title"] = "About";
}

<div id="dashboard-about" class="relative sm:w-full px-2 sm:px-4 lg:px-12 pt-2 sm:pt-4 pb-6 *:mt-4 [&_.note-editor]:text-sm [&_.note-editor]:sm:text-base">

    <!-- PROFILE -->
    <section id="about-profile" class="first:mt-1">
        <div class="section-title flex items-center gap-2 *:grow-0">
            <h6>Profile</h6>
            <button id="profile-form-edit" class="inline" onclick="EditForm(this, 'profile-form')"><i data-feather="edit-3" class="h-4"></i></button>
        </div>
        
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="text-blue-500">@TempData["SuccessMessage"]</div>
        }
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="text-red-500">@TempData["ErrorMessage"]</div>
        }

        <div class="card p-2 sm:p-4 mt-2">
            
            <form id="profile-form" method="post" enctype="multipart/form-data" asp-action="Update" asp-controller="DashboardAbout" data-editable="false" class="*:mt-4">
                <div class="first:mt-0">
                    <label asp-for='Profile.Title' class="label">Title:</label>
                    <input type="text" asp-for='Profile.Title' class="input">
                </div>

                <div class="[&_ul]:list-inside [&_ul]:list-disc [&_ol]:list-inside [&_ol]:list-decimal">
                    <label asp-for='Profile.Description' class="label">Description:</label>
                    <textarea asp-for='Profile.Description' id="summernote"></textarea>
                </div>

                <div>
                    <label asp-for='Profile.Photo' class="label">Photo:</label>
                    <div class="input">
                        <input type="hidden" asp-for='Profile.Photo'>
                        <input type="file" id="profile-photo-input" name="ProfilePhotoFile" accept="image/*">
                        <img id="profile-photo" src='@Model.Profile.Photo' class="w-48 mt-2">
                    </div>
                </div>

                <div>
                    <label asp-for="Profile.CV" class="label">CV:</label>
                    <div class="input">
                        <input type="hidden" asp-for="Profile.CV">
                        <input type="file" name="ProfileCVFile" id="profile-cv-input" accept="pdf/*">
                    @if (Model.Profile.CV != null && Model.Profile.CV != "")
                    {
                        <a href="@Url.Action("DownloadFile", "File", new { fileName = Model.Profile.CV })" class="flex items-start gap-2 mt-2">
                            <img src="/images/pdf.png" alt="Download CV" class="h-12">
                            <div>@Model.Profile.CV</div>
                        </a>
                    }
                    </div>
                </div>

                <div id="profile-form-actions" class="hidden justify-center gap-4 last:mt-8 mb-4">
                    <button type="submit" form="profile-form" class="button button-dark py-1">Save</button>
                    <button type="button" class="button button-light py-1" onclick="CloseForm()">Cancel</button>
                </div>
            </form>
        </div>
    </section>

    <div class="w-full flex justify-end border border-t-black">
        <button class="text-blue-500" onclick="AddSection()">Add Section</button>
    </div>

    @foreach (var Section in Model.Sections)
    {
    @await Html.PartialAsync("/Views/Admin/Dashboard/About/Section.cshtml", Section)
    }
</div>

@section Scripts
{
    <script>
        // set data-editable global attribute on forms
        var forms = document.querySelectorAll('[data-editable]');
        forms.forEach((form) => {
            SetEditable(form, form.dataset.editable);
        })

        // show profile photo dynamically
        const profilePhoto = document.querySelector("#profile-photo");
        const profilePhotoInput = document.querySelector("#profile-photo-input");

        profilePhotoInput.addEventListener("change", (event) => {
            const file = event.target.files[0];

            if (file) {
                const reader = new FileReader();

                reader.onload = function(e) {
                    profilePhoto.src = e.target.result;
                }

                reader.readAsDataURL(file);
            }
        })

        // function for set form editable
        function EditForm(button, formId) {
            var formActionsId = formId + '-actions';

            // set form editable attribute
            const form = document.querySelector("#" + formId);
            form.dataset.editable = "true";
            SetEditable(form, form.dataset.editable)

            // hide edit button
            button.classList.replace("inline", "hidden");

            // show actions button
            const actionsWrapper = document.querySelector("#" + formActionsId)
            actionsWrapper.classList.replace("hidden", "flex");
        }

        // function for set all inputs in form to readonly or disable
        function SetEditable(form, editable) {
            if (editable == "true") {
                $(form).find('input').prop('disabled', false);
                $(form).find('select').prop('disabled', false);
                $(form).find('button').prop('disabled', false);
                $(form).find('button').removeClass('disabled');
                $(form).find('#summernote').summernote('enable');
            }
            else {
                $(form).find('input').prop('disabled', true);
                $(form).find('select').prop('disabled', true);
                $(form).find('button').prop('disabled', true);
                $(form).find('button').addClass('disabled');
                $(form).find('#summernote').summernote('disable');
            }
        }

        // function for close form editing
        function CloseForm() {
            if (confirm('Are you sure you want to cancel form editing?'))
                location.reload();
        }

        // function to confirm delete section or item
        function Delete(event, component) {
            var userConfirmed = confirm('Are you sure you want to delete this ' + component);
            if (!userConfirmed) {
                event.preventDefault();
            }
            return userConfirmed;
        }
    </script>

    <script>
        function AddSection() {
            $.ajax({
                url: '@Url.Action("AddSection", "DashboardAbout")',
                type: 'GET',
                success: (response) => {
                    $('#dashboard-about').append(response);
                }
            })
        }

        function EditSection(url) {
            $.ajax({
                url: url,
                type: 'GET',
                success: (response) => {
                    $('#dashboard-about').append(response);
                }
            })
        }

        function GetSectionItem(url) {
            $.ajax({
                url: url,
                type: 'GET',
                success: (response) => {
                    $('#dashboard-about').append(response);
                }
            })
        }
    </script>

    <script>
        function Reorder(sectionId, itemCount) {
            // show actions button
            const actions = document.querySelector('#' + sectionId + '-reorder-actions');
            actions.classList.replace('hidden', 'inline');

            // show items order button
            const sectionElement = document.querySelector('#' + sectionId);
            const itemsOrderButton = sectionElement.querySelectorAll('.btn-order');
            itemsOrderButton.forEach((item) => {
                item.classList.remove('hidden');
            });

            CheckOrder(sectionId, itemCount);
        }

        function CancelReorder() {
            if (confirm('Are you sure you want to cancel section reordering items?'))
                location.reload();
        }

        function CheckOrder(parentId, itemCount) {
            var parent = document.querySelector('#' + parentId);

            var firstItem = parent.querySelector('.section-item[style="order: 0;"]');
            var firstItemBtn = firstItem.querySelector('.btn-order-up');
            $(firstItemBtn).addClass('disable');
            $(firstItemBtn).prop('disables', 'true');

            var lastItem = parent.querySelector(`.section-item[style="order: ${itemCount-1};"]`);
            var lastItemBtn = lastItem.querySelector('.btn-order-down');
            $(lastItemBtn).addClass('disable');
            $(lastItemBtn).prop('disabled', 'true');
        }

        function OrderUp(elementId, itemCount) {
            var orderNumber = $('#' + elementId).css('order');
            var beforeNumber = Number(orderNumber) - Number(1);

            var item = document.querySelector('#' + elementId);
            var itemBefore = $(item).siblings(`[style="order: ${beforeNumber};"]`);
            itemBefore = itemBefore[0];

            $(itemBefore).css('order', orderNumber);
            $(itemBefore).children('.item-input-order').val(orderNumber);
            $(item).css('order', beforeNumber);
            $(item).children('.item-input-order').val(beforeNumber);

            var btnOrderUp = item.querySelector('.btn-order-up');
            var btnOrderDown = item.querySelector('.btn-order-down');
            var btnOrderUpBefore = itemBefore.querySelector('.btn-order-up');
            var btnOrderDownBefore = itemBefore.querySelector('.btn-order-down');

            if (beforeNumber == 0) {
                $(btnOrderUp).addClass('disable');
                $(btnOrderUp).prop('disabled', 'true');
                $(btnOrderUpBefore).removeClass('disable');
                $(btnOrderUpBefore).removeAttr('disabled');
            }

            if (orderNumber == itemCount - 1) {
                $(btnOrderDown).removeClass('disable');
                $(btnOrderDown).removeAttr('disabled');
                $(btnOrderDownBefore).addClass('disable');
                $(btnOrderDownBefore).prop('disabled', 'true');
            }
        }

        function OrderDown(elementId, itemCount) {
            var orderNumber = $('#' + elementId).css('order');
            var nextNumber = Number(orderNumber) + Number(1);

            var item = document.querySelector('#' + elementId);
            var itemNext = $(item).siblings(`[style="order: ${nextNumber};"]`);
            itemNext = itemNext[0];

            $(itemNext).css('order', orderNumber);
            $(itemNext).children('.item-input-order').val(orderNumber);
            $(item).css('order', nextNumber);
            $(item).children('.item-input-order').val(nextNumber);

            var btnOrderUp = item.querySelector('.btn-order-up');
            var btnOrderDown = item.querySelector('.btn-order-down');
            var btnOrderUpNext = itemNext.querySelector('.btn-order-up');
            var btnOrderDownNext = itemNext.querySelector('.btn-order-down');

            if (orderNumber == 0) {
                $(btnOrderUp).removeClass('disable');
                $(btnOrderUp).removeAttr('disabled');
                $(btnOrderUpNext).addClass('disable');
                $(btnOrderUpNext).prop('disabled', 'true');
            }

            if (nextNumber == itemCount - 1) {
                $(btnOrderDown).addClass('disable');
                $(btnOrderDown).prop('disabled', 'true');
                $(btnOrderDownNext).removeClass('disable');
                $(btnOrderDownNext).removeAttr('disabled');
            }
        }
    </script>
}

Views/Admin/Dashboard/About/Section.cshtml
@model AboutSection

<form id="section_@Model.Id-form-delete" method="post" asp-action="DeleteSection" asp-controller="DashboardAbout" asp-route-id="@Model.Id" onsubmit="return Delete(event, 'section')" hidden></form>
<form id="section_@Model.Id-form-reorder" method="post" asp-action="ReorderSectionItems" asp-controller="DashboardAbout" asp-route-sectionId="@Model.Id" hidden></form>

<section id="section_@Model.Id">
    <input type="hidden" form="section_@Model.Id-form-reorder" asp-for="Id">

    <div class="section-title flex items-center gap-2">
        <h6>@Model.Title</h6>
        <div class="flex items-center">
            <button type="button" onclick="EditSection('@Url.Action("EditSection", "DashboardAbout", new { id = Model.Id })')"><i data-feather="edit-3" class="h-4"></i></button>
            <button type="submit" form="section_@Model.Id-form-delete"><i data-feather="trash" class="h-4 text-red-500"></i></button>
        </div>
    </div>

    <div class="card p-2 sm:p-4 mt-2">
        <div class="flex gap-2 *:grow-0">
            <label class="label">Items:</label>
            <div class="*:me-1">
                <button type="button" class="inline text-sm hover:text-blue-900 underline" onclick="GetSectionItem('@Url.Action("AddSectionItem", "DashboardAbout", new { sectionId = Model.Id })')">add</button>
                <div class="inline">
                    <button type="button" class="inline text-sm hover:text-blue-900 underline" onclick="Reorder('section_@Model.Id', @Model.Items.Count)">reorder</button>
                    <div id="section_@Model.Id-reorder-actions" class="hidden text-sm">:
                        <button type="submit" form="section_@Model.Id-form-reorder" class="text-blue-500 hover:text-blue-600">save</button>
                        <button type="button" class="text-yellow-500 hover:text-yellow-600" onclick="CancelReorder()">cancel</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="grid grid-cols-1 gap-2">
        @foreach (var Item in Model.Items)
        {
            <div id="section_@Model.Id-item_@Item.Id" class="section-item flex items-start justify-between gap-1 sm:gap-2" style="order: @Item.Id;">
                <input type="hidden" form="section_@Model.Id-form-reorder" asp-for="Items[Item.Id].Id">
                <input type="hidden" form="section_@Model.Id-form-reorder" asp-for="Items[Item.Id].Order" class="item-input-order">
                
                <form id="section_@Model.Id-item_@Item.Id-form-delete" method="post" asp-action="DeleteSectionItem" asp-controller="DashboardAbout" asp-route-sectionId="@Model.Id" asp-route-itemId="@Item.Id" onsubmit="return Delete(event, 'item')" hidden></form>
                
                <div class="w-56 grow border border-gray-200 text-sm sm:text-base p-2 sm:p-4">
                    <h6 class="text-sm sm:text-base">@Item.Name</h6>

                    @if (Item.Company != null || Item.From != null)
                    {
                    <div class="mt-1 text-xs sm:text-sm text-gray-500">
                        <span>@Item.Company</span> <span>@(@Item.From != null ? "|" : null)</span> <span>@Item.From?.ToString("MMMM yyyy")</span> <span>@(Item.To != null ? "-" : null)</span> <span>@Item.To?.ToString("MMMM yyyy")</span>
                    </div>
                    }

                    @if (Item.Description != null)
                    {
                    <div class="[&_ul]:list-inside [&_ul]:list-disc [&_ol]:list-inside [&_ol]:list-decimal mt-2">@Html.Raw(Item.Description)</div>
                    }
                </div>

                <div class="flex-none flex flex-col gap-2 mt-0 sm:mt-2">
                    <button type="button" onclick="GetSectionItem('@Url.Action("EditSectionItem", "DashboardAbout", new { sectionId = Model.Id, itemId = Item.Id })')" class="hover:text-blue-900"><i data-feather="edit-3" class="h-4"></i></button>
                    <button type="button" class="btn-order btn-order-up hidden hover:text-blue-900" onclick="OrderUp('section_@Model.Id-item_@Item.Id', @Model.Items.Count)"><i data-feather="arrow-up" class="h-4"></i></button>
                    <button type="button" class="btn-order btn-order-down hidden hover:text-blue-900" onclick="OrderDown('section_@Model.Id-item_@Item.Id', @Model.Items.Count)"><i data-feather="arrow-down" class="h-4"></i></button>
                    <button type="submit" form="section_@Model.Id-item_@Item.Id-form-delete" class="text-red-500 hover:text-red-600"><i data-feather="trash" class="h-4"></i></button>
                </div>
            </div>
        }
        </div>
    </div>
</section>

Views/Admin/Dashboard/About/_SectionForm.cshtml
@model AboutSection
@{
    var SubmitText = "";
    if (ViewBag.Session == "Add")
        SubmitText = "Add";
    if (ViewBag.Session == "Edit")
        SubmitText = "Save";
}

<div id="section-form" class="fixed -top-4 right-0 bottom-0 left-0 backdrop-blur-sm bg-white/30 flex justify-center items-center">
    <div class="card sm:w-96 p-2 sm:p-4">
        <form method="post" asp-action="@ViewBag.Action" asp-controller="DashboardAbout">
            <input type="hidden" asp-for='Id'>

            <div>
                <label class="label">Section Title:</label>
                <input type="text" class="input" asp-for='Title' placeholder="Title..." required>
                <span asp-validation-for="Title" class="text-sm text-red-500"></span>
            </div>

            <div class="flex flex-col sm:flex-row items-stretch sm:justify-center gap-2 sm:gap-4 mt-4 sm:mt-8">
                <button type="submit" class="button button-dark py-1">@SubmitText</button>
                <button type="button" class="button button-light py-1" onclick="document.querySelector('#section-form').remove()">Cancel</button>
            </div>
        </form>
    </div>

    <script>
        $(document).ready(() => {
            $('#Title').focus();
        })
    </script>
</div>